# on:
#   #push:
#   workflow_dispatch:
#     inputs:
#       branch_name:
#         required: true
#         type: string
#       PR_ISSUE_NUMBER:
#         required: true
#         type: string
#       PR_REPO_OWNER:
#         required: true
#         type: string 
#       PR_REPO_NAME:
#         required: true
#         type: string   
# env:
#   username: "${{github.actor}}"
#   branch: "${{ github.event.inputs.branch_name }}"
  
# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps: 
    
#     - uses: oNaiPs/secrets-to-env-action@v1
#       with:
#         secrets: ${{ toJSON(secrets) }}
   
#     - name: Checkout  
#       uses: actions/checkout@v1

#     - name: Setup .NET Core
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 6.0.x

#     - name: Build
#       run: dotnet build --configuration Release

#     - name: Execute Regression Test
#       run: dotnet test --logger "trx;LogFileName=test-results.trx"

#     - name: Generate Regression Test Report
#       id : report
#       uses: dorny/test-reporter@v1
#       if: always()
#       with:
#         name: Regression Test Report
#         path: "**/test-results.trx"                            
#         reporter: dotnet-trx     
#         fail-on-error: true
    
#     # - name: Comment on Main PR
#     #   uses: actions/github-script@v5
#     #   with:
#     #     github-token: ${{secrets.PAT_TOKEN}}
#     #     # run: echo 'owner ${{ github.event.inputs.PR_REPO_OWNER }} prreponame:${{ github.event.inputs.PR_REPO_NAME }}  '

        
#     #     script: |
#     #         const issue_number = parseInt('${{ inputs.PR_ISSUE_NUMBER }}');
#     #         const repo_owner = "${{ inputs.PR_REPO_OWNER }}";
#     #         const repo_name = "${{ inputs.PR_REPO_NAME }}";

    
#     #         github.rest.issues.createComment({
#     #           issue_number: issue_number,
#     #           owner: repo_owner,
#     #           repo: repo_name,
#     #            body: `🎉 Test Results 🎉

#     #                   ✅ Passed: ${{ steps.report.outputs.passed }}
#     #                   ❌ Failed: ${{ steps.report.outputs.failed }}
#     #                   ⏭️ Skipped: ${{ steps.report.outputs.skipped }}
                      
#     #                   Keep up the good work! 👍`
#     #         })

name: non-trial env testing

on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
        type: string
      PR_ISSUE_NUMBER:
        required: true
        type: string
      PR_REPO_OWNER:
        required: true
        type: string 
      PR_REPO_NAME:
        required: true
        type: string   

env:
  username: "${{github.actor}}"
  branch: "${{ github.event.inputs.branch_name }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}

    - name: Checkout  
      uses: actions/checkout@v2

    - name: Navigate to Live Folder
      run: cd non-trial

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Execute Test And Generate Test Report
      id: report
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: non-trial/TestAutomation
        report_name: Non-TrialEnvTestResult
        report_title: Non Trial Environment
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gist_name: Non-TrialEnvTestResult.md
        gist_badge_label: 'Result: %Counters_passed%/%Counters_total%'
        set_check_status_from_test_outcome: true
        fail_build_on_failed_tests: true
        gist_token: ${{ secrets.PAT_TOKEN }}
